// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuqdVG5h0TJSr-mzBvH2HVTLdpixJwVgQ',
    appId: '1:83397990435:android:91a60afca859d383b77996',
    messagingSenderId: '83397990435',
    projectId: 'hw-firebase-week18',
    databaseURL: 'https://hw-firebase-week18-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hw-firebase-week18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo-fTI-03iV4ANoW7TwMJL9g1tFqrdZV0',
    appId: '1:83397990435:ios:6dee166f6ebbf479b77996',
    messagingSenderId: '83397990435',
    projectId: 'hw-firebase-week18',
    databaseURL: 'https://hw-firebase-week18-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hw-firebase-week18.appspot.com',
    iosClientId: '83397990435-r6dnpuo2tvhk31nrnudt8db20t4ifpob.apps.googleusercontent.com',
    iosBundleId: 'com.example.hwFirebaseWeek18',
  );
}
